// Chain & network configuration for Urban Wallet
export const CHAINS = {
  ethereum: {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'ETH',
    chainId: 1,
    rpc: 'https://ethereum-rpc.publicnode.com',
    explorer: 'https://etherscan.io',
    decimals: 18,
    icon: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    color: '#627eea',
    evmCompatible: true,
  },
  bsc: {
    id: 'bsc',
    name: 'BNB Smart Chain',
    symbol: 'BNB',
    chainId: 56,
    rpc: 'https://bsc-dataseed1.binance.org/',
    explorer: 'https://bscscan.com',
    decimals: 18,
    icon: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png',
    color: '#f0b90b',
    evmCompatible: true,
  },
  tron: {
    id: 'tron',
    name: 'Tron',
    symbol: 'TRX',
    chainId: null,
    rpc: 'https://api.trongrid.io',
    explorer: 'https://tronscan.org',
    decimals: 6,
    icon: 'https://assets.coingecko.com/coins/images/1094/small/tron-logo.png',
    color: '#ff0013',
    evmCompatible: false, // TronGrid is not a standard JSON-RPC; needs TronWeb SDK
  },
}

export const DEFAULT_TOKENS = [
  {
    symbol: 'USDD',
    name: 'USD-D Token',
    contractAddress: '0x82c400bE990EfE6CD44B5E572c1a4Cf8D3B935b3',
    chain: 'bsc',
    decimals: 18,
    icon: '/usddlogo.png',
    coingeckoId: 'usdd',
    priceUsd: 0.000006727,
    isDefault: true,
  },
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    contractAddress: null,
    chain: 'ethereum',
    decimals: 8,
    icon: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png',
    coingeckoId: 'bitcoin',
    priceUsd: 0,
    isNative: false,
    isDefault: true,
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    contractAddress: null,
    chain: 'ethereum',
    decimals: 18,
    icon: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    coingeckoId: 'ethereum',
    priceUsd: 0,
    isNative: true,
    isDefault: true,
  },
  {
    symbol: 'BNB',
    name: 'BNB',
    contractAddress: null,
    chain: 'bsc',
    decimals: 18,
    icon: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png',
    coingeckoId: 'binancecoin',
    priceUsd: 0,
    isNative: true,
    isDefault: true,
  },
  {
    symbol: 'USDT',
    name: 'Tether USD',
    contractAddress: '0x55d398326f99059fF775485246999027B3197955',
    chain: 'bsc',
    decimals: 18,
    icon: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
    coingeckoId: 'tether',
    priceUsd: 1,
    isDefault: true,
  },
  {
    symbol: 'USDC',
    name: 'USD Coin',
    contractAddress: '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d',
    chain: 'bsc',
    decimals: 18,
    icon: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
    coingeckoId: 'usd-coin',
    priceUsd: 1,
    isDefault: true,
  },
  {
    symbol: 'TRX',
    name: 'Tron',
    contractAddress: null,
    chain: 'tron',
    decimals: 6,
    icon: 'https://assets.coingecko.com/coins/images/1094/small/tron-logo.png',
    coingeckoId: 'tron',
    priceUsd: 0,
    isNative: true,
    isDefault: true,
  },
]

export const ERC20_ABI = [
  'function balanceOf(address owner) view returns (uint256)',
  'function transfer(address to, uint256 amount) returns (bool)',
  'function decimals() view returns (uint8)',
  'function symbol() view returns (string)',
  'function name() view returns (string)',
  'function totalSupply() view returns (uint256)',
  'function allowance(address owner, address spender) view returns (uint256)',
  'function approve(address spender, uint256 amount) returns (bool)',
]

export const CURRENCIES = [
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
]
